// =====COPYRIGHT=====
// github http copyright text
// =====COPYRIGHT=====
// This file is used by Code Analysis to maintain SuppressMessage 
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given 
// a specific target and scoped to a namespace, type, member, etc.
//
// To add a suppression to this file, right-click the message in the 
// Error List, point to "Suppress Message(s)", and click 
// "In Project Suppression File".
// You do not need to add suppressions to this file manually.

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA2210:AssembliesShouldHaveValidStrongNames")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Globalization", "CA1303:Do not pass literals as localized parameters", MessageId = "System.Web.UI.WebControls.Literal.set_Text(System.String)", Scope = "member", Target = "Srs.WebPlatform.WebServices.Printer.Default.#ButtonExportImage_Click(System.Object,System.EventArgs)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Globalization", "CA1303:Do not pass literals as localized parameters", MessageId = "System.Web.UI.WebControls.Literal.set_Text(System.String)", Scope = "member", Target = "Srs.WebPlatform.WebServices.Printer.Default.#ButtonExportPdf_Click(System.Object,System.EventArgs)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1014:MarkAssembliesWithClsCompliant")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Reliability", "CA2000:Dispose objects before losing scope", Scope = "member", Target = "Srs.WebPlatform.WebServices.Printer.HeartBeatService.#ConvertUrlToPdf(System.String,System.String,System.Int32,System.Int32)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA2204:Literals should be spelled correctly", MessageId = "src", Scope = "member", Target = "Srs.WebPlatform.WebServices.Printer.Default.#ButtonExportPdf_Click(System.Object,System.EventArgs)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA2204:Literals should be spelled correctly", MessageId = "sessionTokenId", Scope = "member", Target = "Srs.WebPlatform.WebServices.Printer.Default.#ButtonExportPdf_Click(System.Object,System.EventArgs)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA2204:Literals should be spelled correctly", MessageId = "runat", Scope = "member", Target = "Srs.WebPlatform.WebServices.Printer.Default.#ButtonExportPdf_Click(System.Object,System.EventArgs)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA2204:Literals should be spelled correctly", MessageId = "ConvertUrlToPdf", Scope = "member", Target = "Srs.WebPlatform.WebServices.Printer.Default.#ButtonExportPdf_Click(System.Object,System.EventArgs)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA2204:Literals should be spelled correctly", MessageId = "marginLeft", Scope = "member", Target = "Srs.WebPlatform.WebServices.Printer.Default.#ButtonExportPdf_Click(System.Object,System.EventArgs)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA2204:Literals should be spelled correctly", MessageId = "marginTop", Scope = "member", Target = "Srs.WebPlatform.WebServices.Printer.Default.#ButtonExportPdf_Click(System.Object,System.EventArgs)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA2204:Literals should be spelled correctly", MessageId = "pdfViewer", Scope = "member", Target = "Srs.WebPlatform.WebServices.Printer.Default.#ButtonExportPdf_Click(System.Object,System.EventArgs)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1702:CompoundWordsShouldBeCasedCorrectly", MessageId = "HeartBeat", Scope = "member", Target = "Srs.WebPlatform.WebServices.Printer.IHeartbeatMonitoringServiceV1.#HeartBeat()")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1031:DoNotCatchGeneralExceptionTypes", Scope = "member", Target = "Srs.WebPlatform.WebServices.Printer.HeartbeatService.#ConvertUrlToPdf(System.String,System.String,System.Int32,System.Int32)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Reliability", "CA2000:Dispose objects before losing scope", Scope = "member", Target = "Srs.WebPlatform.WebServices.Printer.PrintService.#Srs.WebPlatform.WebServices.Printer.IPrintServiceV1.ConvertUrlToPdf(System.String,System.String,System.Int32,System.Int32)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1031:DoNotCatchGeneralExceptionTypes", Scope = "member", Target = "Srs.WebPlatform.WebServices.Printer.PrintService.#IsQualifiedUrl(System.String)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1031:DoNotCatchGeneralExceptionTypes", Scope = "member", Target = "Srs.WebPlatform.WebServices.Printer.PrintService.#GenerateImages(System.Object)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Reliability", "CA2000:Dispose objects before losing scope", Scope = "member", Target = "Srs.WebPlatform.WebServices.Printer.PrintService.#GetNumberOfPages(System.String,System.String,System.Int32,System.Int32)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1822:MarkMembersAsStatic", Scope = "member", Target = "Srs.WebPlatform.WebServices.Printer.PrintService.#ConvertPdfToImage(System.String,System.Int32,System.Int32,System.Int32)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1054:UriParametersShouldNotBeStrings", MessageId = "0#", Scope = "member", Target = "Srs.WebPlatform.WebServices.Printer.PrintService.#IsQualifiedUrl(System.String)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1054:UriParametersShouldNotBeStrings", MessageId = "0#", Scope = "member", Target = "Srs.WebPlatform.WebServices.Printer.PrintService.#IsPdfUrl(System.String)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields", Scope = "member", Target = "Srs.WebPlatform.WebServices.Printer.PrintService.#_url")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1054:UriParametersShouldNotBeStrings", MessageId = "1#", Scope = "member", Target = "Srs.WebPlatform.WebServices.Printer.IPrintServiceV1.#GetNumberOfPages(System.String,System.String,System.Int32,System.Int32)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1054:UriParametersShouldNotBeStrings", MessageId = "1#", Scope = "member", Target = "Srs.WebPlatform.WebServices.Printer.IPrintServiceV1.#ConvertUrlToPdf(System.String,System.String,System.Int32,System.Int32)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1054:UriParametersShouldNotBeStrings", MessageId = "1#", Scope = "member", Target = "Srs.WebPlatform.WebServices.Printer.IPrintServiceV1.#ConvertUrlToImage(System.String,System.String,System.Int32,System.Int32,System.String,System.Int32)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1054:UriParametersShouldNotBeStrings", MessageId = "2#", Scope = "member", Target = "Srs.WebPlatform.WebServices.Printer.HeartbeatService.#GetNumberOfPages(System.String,System.String,System.String,System.Int32,System.Int32)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA1801:ReviewUnusedParameters", MessageId = "extension", Scope = "member", Target = "Srs.WebPlatform.WebServices.Printer.HeartbeatService.#ConvertUrlToImage(System.String,System.String,System.String,System.Int32,System.Int32,System.String,System.Int32)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1822:MarkMembersAsStatic", Scope = "member", Target = "Srs.WebPlatform.WebServices.Printer.HeartbeatService.#ConvertUrlToImage(System.String,System.String,System.String,System.Int32,System.Int32,System.String,System.Int32)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode", Scope = "member", Target = "Srs.WebPlatform.WebServices.Printer.Default.#GetImageFormat(System.String)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1822:MarkMembersAsStatic", Scope = "member", Target = "Srs.WebPlatform.WebServices.Printer.PrintService.#IsPdfUrl(System.String)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA1801:ReviewUnusedParameters", MessageId = "extension", Scope = "member", Target = "Srs.WebPlatform.WebServices.Printer.HeartbeatService.#GetNumberOfPages(System.String,System.String,System.String,System.Int32,System.Int32)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1822:MarkMembersAsStatic", Scope = "member", Target = "Srs.WebPlatform.WebServices.Printer.HeartbeatService.#GetNumberOfPages(System.String,System.String,System.String,System.Int32,System.Int32)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1054:UriParametersShouldNotBeStrings", MessageId = "1#", Scope = "member", Target = "Srs.WebPlatform.WebServices.Printer.HeartbeatService.#ConvertUrlToPdf(System.String,System.String,System.Int32,System.Int32)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1822:MarkMembersAsStatic", Scope = "member", Target = "Srs.WebPlatform.WebServices.Printer.HeartbeatService.#ConvertUrlToPdf(System.String,System.String,System.Int32,System.Int32)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1054:UriParametersShouldNotBeStrings", MessageId = "2#", Scope = "member", Target = "Srs.WebPlatform.WebServices.Printer.HeartbeatService.#ConvertUrlToImage(System.String,System.String,System.String,System.Int32,System.Int32,System.String,System.Int32)")]
